### ISSUE TITLE
CCU REST API Deprecation

### ISSUE THREAD

**Issue by ghost** [Velir/akamai-ccu-rest-api-connector#2]
Hello!

I'm an API evangelist for Akamai, and wanted to make sure you're aware that the REST CCU API will be deprecated soon - you need to update the library to use the new OPEN framework.  As a bonus, when the fast invalidate (5 seconds) purge is released this summer, the authentication will be the same and the endpoint will be similar.

You can find some documentation here:
https://community.akamai.com/community/developer/blog/2015/08/20/getting-started-with-the-v2-open-ccu-api

Thanks!
Kirsten

**Comment by kairas** [comment]
Thank you for bringing this to our attention. I've completed this in the pull request https://github.com/Velir/akamai-ccu-rest-api-connector/pull/3 which we will accept once it is fully tested.
