### ISSUE TITLE
AEM 6.2 Compatible Version

### ISSUE THREAD

**Issue by kmersmann** [Velir/akamai-ccu-rest-api-connector#4]
Hi,

We're currently using this tool in our AEM 6.0 implementation, and it's working great. We're in the process of upgrading to AEM 6.2. We noticed the latest CCU connector release is not compatible with 6.2. It appears the org.apache.sling.event version running in 6.2 was updated to 4.0, while the CCU connector is dependent on 3.3.4. 

Would like to know if you're working on updating the tool to be compatible with 6.2?

Thanks!

-Keith

**Comment by kairas** [comment]
I'll take a look: this shouldn't be very difficult at all.

**Comment by kmersmann** [comment]
Excellent, thanks!

**Comment by kairas** [comment]
Can you give the snapshot release on branch 6.2 a test? Seems fine to me. I can do a release to master at any time.

**Comment by kmersmann** [comment]
Thank you for working on this so quickly and I'm sorry it's taken me so long to get back to you... I pulled down the 6.2 branch and attempted to compile with maven. It's giving me an error when attempting to pull in a dependency:

Could not resolve dependencies for project com.
velir.aem:akamai-ccu-rest-api-connector:bundle:2.2-SNAPSHOT: Could not find artifact com.adobe.granite:com.adobe.granite
.replication.core:jar:6.0.14 in central (https://repo.adobe.com/nexus/content/groups/public)

Am I doing something wrong when compiling?

Thanks again for your help,
Keith

**Comment by kairas** [comment]
Odd... It must have been in Adobe's nexus as some point since I was able to compile. That is the replication core version used in 6.2.... https://repo.adobe.com/nexus/content/groups/public/com/adobe/granite/com.adobe.granite.replication.core/ don't see it though. 

The only use of this dependency is a string constant so it can be removed with no issue.

**Comment by kairas** [comment]
I pushed the fix

**Comment by kmersmann** [comment]
That did the trick, much appreciated!! I'm going to install this in our test environment and let you know how it goes.

**Comment by kmersmann** [comment]
This is working great in our 6.2 / Akamai integrated environment. I appreciate the help!

Do you plan on implementing the new fast purge method in the future?

Thanks,
Keith

**Comment by kairas** [comment]
@kmersmann  Its been a long while but I finally got around to introducing fast purge. https://github.com/Velir/akamai-ccu-rest-api-connector/pull/9
